// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSL5tzJSavb3Zfuz-uAjMpQRe2rmX6HvQ',
    appId: '1:957609247035:web:a248e2b7fee3436789771e',
    messagingSenderId: '957609247035',
    projectId: 'mynotes-flutter-bishal',
    authDomain: 'mynotes-flutter-bishal.firebaseapp.com',
    storageBucket: 'mynotes-flutter-bishal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjphYNUstHIPY6T8to-RucX44KfKEHPw',
    appId: '1:957609247035:android:ef184858485dd89b89771e',
    messagingSenderId: '957609247035',
    projectId: 'mynotes-flutter-bishal',
    storageBucket: 'mynotes-flutter-bishal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrNTQqCCiVnG9aJljh4z0BbfpL_Dgfvc',
    appId: '1:957609247035:ios:89b2029b3650ddff89771e',
    messagingSenderId: '957609247035',
    projectId: 'mynotes-flutter-bishal',
    storageBucket: 'mynotes-flutter-bishal.appspot.com',
    iosClientId: '957609247035-eip8ulj6pq7bgrdhuh1jbi8o08a17833.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrNTQqCCiVnG9aJljh4z0BbfpL_Dgfvc',
    appId: '1:957609247035:ios:26a46378337bc6b189771e',
    messagingSenderId: '957609247035',
    projectId: 'mynotes-flutter-bishal',
    storageBucket: 'mynotes-flutter-bishal.appspot.com',
    iosClientId: '957609247035-kcqm65p13nbtc403b0mejrt4sptbu8vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects.RunnerTests',
  );
}
